### ISSUE TITLE
Failed to activate the syntax-neonize package

### ISSUE THREAD

**Issue by BinarySoul** [youngmoon01/syntax-neonize#1] opened 2022-12-09 08:25 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.63.2022120905 x64
**Electron**: 12.2.3
**OS**: VOIDSTATION
**Thrown From**: [syntax-neonize](https://github.com/youngmoon01/syntax-neonize) package 3.3.0

### Stack Trace

Failed to activate the syntax-neonize package

```
At sheets is not defined

ReferenceError: sheets is not defined
    at SyntaxNeonize.neonize (syntax-neonize.js:26:11)
    at SyntaxNeonize.activate (syntax-neonize.js:166:10)
    at Package.activateNow (/app.asar/src/package.js:242:27)
    at /app.asar/src/package.js:211:27
    at Package.measure (/app.asar/src/package.js:82:19)
    at /app.asar/src/package.js:205:14
    at new Promise (<anonymous>)
    at Package.activate (/app.asar/src/package.js:203:32)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:780:36)
    at /app.asar/node_modules/settings-view/lib/package-manager.coffee:321:25
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.coffee:68:7)
    at triggerExitCallback (/app.asar/src/buffered-process.js:280:9)
    at /app.asar/src/buffered-process.js:310:9)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

### Commands

```
```

### Non-Core Packages

```
80-game-neon 2.1.0 
80-game-neon-ui 2.1.0 
80-synth-neon 2.7.0 
80-synth-neon-ui 2.2.0 
atom-neon-ui 0.37.1 
blue-neon-syntax 1.2.0 
monokai-neon-syntax 0.0.1 
neon 0.2.0 
neon-color-scheme 1.0.0 
neon-cursor 1.6.0 
neon-drakula-syntax 0.2.0 
neon-selection 0.3.2 
neon-syntax 0.3.7 
SkriptDark-Neon-Syntax 2.1.2 
SkriptLight-Neon-Syntax 2.1.4 
syntax-neonize 3.3.0 
```

**Comment by mikey-** [comment] 2023-04-11 06:07
This is easy enough to fix, I believe that sheets and a few other variables just need to be declared - using `let`, `var`, `const` or whatever is appropriate. I think in most cases `let` makes sense.

**Comment by youngmoon01** [comment] 2023-04-12 15:20
I guess the issue is now fixed after PR from @mikey- has merged. I appreciate your contributions!

**Closed as completed by youngmoon01** 2023-04-12 15:20 UTC
